### ISSUE TITLE
Could not establish trust relationship for the SSL/TLS secure channel with authority 'rdws.rd.go.th'.

### ISSUE THREAD

**Issue by ninyawee** [ZenateConnect/RevenueDepartmentService#2]
ไม่ทราบว่าเกิดจากอะไร ผมไม่ค่อยคล่อง c# ครับ พยายามหาว่า certificate เอามาใช้ต่อไหน หาไม่เจอ

แต่ verify ละว่าตรงกับที่กรมให้
```
{
  "title": "API Error! - Internal Server Error",
  "message": "Could not establish trust relationship for the SSL/TLS secure channel with authority 'rdws.rd.go.th'.",
  "statusCode": "500",
  "value": null
}
```

**Comment by ninyawee** [comment]
https://github.com/ZenateConnect/RevenueDepartmentService/blob/1676a9856d01eaf95e0ba970c2cf186b3be61a7c/RevenueService.Api/Controllers/VATServiceController.cs#L40-L45

แล้วก็ลองแก้พวกนี้ตามเครื่องของผม ก็ใช้ไม่ได้เหมือนเดิม

**Comment by ninyawee** [comment]
ใครอยากใช้ soap ไปพลางๆผมทำ script python ง่ายไปลองได้ครับ https://github.com/CircleOnCircles/rd_soap

**Comment by sixnaskunz** [comment]
ขอโทษด้วยนะครับที่ตอบช้า สำหรับปัญหานี้จะเกี่ยวกับการ Add Trusted Root Certification Authorities
เบื้องต้นให้เราติดตั้ง Cer ทั้งสองตัวคือ adhq1.cer และ ADHQ5.cer ก่อน โดยดาวน์โหลดจากลิงค์ด้านล่าง
ถ้าหากยังไม่สามารถเรียก API กรมสรรพากรได้ ให้ทำการ Add Certification ที่ชื่อ adhq1.cer เข้าไปที่ Trusted Root Certification Authorities ก่อนจึงจะสามารถใช้งาน API ของทางกรมสรรพากรได้ หรือ สามารถดาวน์โหลดได้ที่ [Client Certification](https://www.rd.go.th/fileadmin/images/image_webservices/Download_Cert_071260.zip)

ส่วนวิธี Add Trusted Root Certification Authorities สำหรับ Windows 10 นะครับ
1. เปิด Run > certlm.msc หรือ กด Start แล้ว Search พิมพ์ว่า "Certificates" แล้วเลือก Manage User Certificates
2. หาเมนูที่ชื่อ Trusted Root Certification Authorities > Certificates
3. คลิกขวาที่ Certificates เลือก Import และเลือกที่อยู่ของ adhq1.cer ตัวนี้
